[
  "app/tests/test_app.py::test_add_session",
  "app/tests/test_app.py::test_add_session_unknown_player",
  "app/tests/test_app.py::test_get_all_players",
  "app/tests/test_app.py::test_get_single_player",
  "app/tests/test_app.py::test_get_unknown_player_returns_404",
  "app/tests/test_app.py::test_health_check",
  "app/tests/test_app.py::test_index_returns_200",
  "app/tests/test_app.py::test_leaderboard",
  "app/tests/test_app.py::test_metrics_endpoint"
]